class FeatureColumnNames:
    def __init__(self):
        self.open_price: str = "open"
        self.high_price: str = "high"
        self.low_price: str = "low"
        self.close_price: str = "close"
        self.volume: str = "volume"
        self.percent_b: str = "percent_b"
        self.atr: str = "atr"
        self.macd: str = "macd"
        self.macd_signal: str = "macd_signal"
        self.macd_hist: str = "macd_hist"
        self.adx: str = "adx"
        self.sma: str = "sma"
        self.ema: str = "ema"
        self.rsi: str = "rsi"
        self.fast_stochastic: str = "%K"
        self.slow_stochastic: str = "%D"
        self.vpt: str = "vpt"
        self.day: str = "day"
        self.hour: str = "hour"
        self.open_change: str = "open change"
        self.high_change: str = "high change"
        self.low_change: str = "low change"
        self.close_change: str = "close change"
        self.open_trend: str = "open trend"
        self.high_trend: str = "high trend"
        self.low_trend: str = "low trend"
        self.close_trend: str = "close trend"
        self.price_movement: str = "price movement"
        self.price_range: str = "price range"
        self.price_trend: str = "price trend"

